import assert from 'node:assert/strict';
import {createOutlineEditor,outlineIssue,circlePoints} from '../js/outline-editor.js';
import {writeDXF,readDXF} from '../js/dxf.js';
const original=[{type:'poly',closed:true,pts:[{x:0,y:0},{x:40,y:0},{x:40,y:30},{x:0,y:30}]}];
const editor=createOutlineEditor(original);
editor.begin();editor.entities[0].pts[1].x=45;editor.commit();
assert.equal(original[0].pts[1].x,40,'preview corrections must not mutate the imported outline');
assert.equal(editor.dirty,true);editor.undo();assert.equal(editor.dirty,false);editor.redo();assert.equal(editor.entities[0].pts[1].x,45);
editor.begin();editor.entities[0].pts[1].x=70;editor.cancel();assert.equal(editor.entities[0].pts[1].x,45,'cancelled pointer restores its prior geometry');
editor.reset();assert.equal(editor.dirty,false);editor.undo();assert.equal(editor.entities[0].pts[1].x,45,'reset itself can be undone');
editor.undo();editor.begin();editor.entities.push({type:'circle',c:{x:10,y:10},r:3});editor.commit();assert.equal(editor.canRedo,false,'new corrections discard the old redo branch');
assert.equal(outlineIssue(editor.entities),'');
assert.match(outlineIssue([{type:'poly',closed:true,pts:[{x:0,y:0},{x:20,y:20},{x:0,y:20},{x:20,y:0}]}]),/crosses/);
assert.match(outlineIssue([]),/at least one/);
assert.match(outlineIssue([{type:'poly',closed:true,pts:[{x:0,y:0},{x:20,y:0},{x:20,y:0},{x:0,y:20}]}]),/overlap/);
const corrected=editor.entities.map(e=>({...e,layer:'L0'}));
const parsed=readDXF(writeDXF(corrected,[{id:'L0',name:'Part',color:'#fff'}],{}));
assert.equal(parsed.entities.length,2);assert.equal(parsed.entities[0].pts[1].x,40);assert.equal(parsed.entities[1].r,3);
const circle={type:'circle',c:{x:30,y:20},r:10};
assert.equal(outlineIssue([{type:'poly',closed:true,pts:circlePoints(circle)}]),'');
console.log('PASS: outline edit history, cancelled edits, input preservation, invalid contours and corrected DXF export');
