import assert from 'node:assert/strict';
import * as W from '../js/workflows.js';
import * as G from '../js/geom.js';
const p = (x, y) => ({ x, y });
const line = (a, b, id = 'a', layer = 'L0') => ({ type: 'line', a, b, id, layer });
const near = (a, b, tol = 1e-7) => assert.ok(Math.abs(a - b) < tol, `${a} != ${b}`);
const source = [p(0, 0), p(30, 0), p(5, 20)];
const target = source.map(q => G.rotatePt(q, p(0, 0), Math.PI / 3)).map(q => p(q.x + 100, q.y - 40));
const alignment = W.rigidAlignment(source, target);
near(alignment.max, 0); near(alignment.angle, Math.PI / 3);
source.forEach((q, i) => near(G.dist(alignment.point(q), target[i]), 0));
const arc = { type: 'arc', c: p(12, 3), r: 10, a0: 0, a1: Math.PI, id: 'arc', layer: 'L0' };
near(alignment.entity(arc).r, 10);
assert.ok(W.rigidAlignment(source, target.map((q, i) => i === 2 ? p(q.x + 4, q.y) : q)).max > 1);
assert.throws(() => W.rigidAlignment([p(0, 0), p(0, 0)], [p(0, 0), p(1, 1)]));
const dev = W.traceDeviation([p(0, 1), p(10, 2)], [line(p(0, 0), p(10, 0))]); near(dev.max, 2); near(dev.rms, Math.sqrt(2.5));
const square = [line(p(0, 0), p(10, 0), '1'), line(p(10, 0), p(10, 10), '2'), line(p(10, 10), p(0, 10), '3'), line(p(0, 10), p(0, 0), '4')];
assert.deepEqual(W.auditContours(square), []);
assert.ok(W.auditContours([square[0], { ...square[0], id: 'dup' }]).some(i => i.kind === 'duplicate edge'));
assert.ok(W.auditContours([line(p(0, 0), p(10, 10)), line(p(0, 10), p(10, 0), 'b')]).some(i => i.kind === 'intersection'));
assert.ok(W.auditContours([{ type: 'poly', pts: [p(0, 0), p(10, 10), p(0, 10), p(10, 0)], closed: true, id: 'bow' }]).some(i => i.kind === 'intersection'));
assert.ok(W.auditContours([line(p(0, 0), p(0, 0))]).some(i => i.kind === 'zero length'));
assert.ok(!W.auditContours([arc, { ...arc, a0: Math.PI, a1: 2 * Math.PI, id: 'other' }]).some(i => i.kind === 'duplicate edge'));
const gap = [line(p(0, 0), p(10, 0)), line(p(10.2, 0), p(20, 0), 'b')];
assert.ok(W.auditContours(gap).some(i => i.kind === 'gap' && Math.abs(i.distance - 0.2) < 1e-8));
const joined = W.joinContours(square); assert.equal(joined.entities.length, 1); assert.equal(joined.entities[0].closed, true); near(G.polyAreaPerimeter(joined.entities[0]).area, 100);
const bridged = W.joinContours(gap); assert.equal(bridged.entities.length, 1); assert.equal(bridged.bridges, 1); assert.equal(bridged.entities[0].pts.length, 4);
const separate = W.joinContours([gap[0], { ...gap[1], layer: 'L1' }]); assert.equal(separate.entities.length, 2);
const curved = W.joinContours([arc, line(p(-10 + 12, 3), p(12, 3), 'l')]); assert.equal(curved.entities.length, 1);
near(G.polyToSegments(curved.entities[0])[0].r, 10);
const reversed = W.joinContours([line(p(12, -5), p(22, 3)), arc]);
assert.ok(G.polyToSegments(reversed.entities[0]).some(s => s.type === 'arc' && Math.abs(s.r - 10) < 1e-7));
assert.ok(W.auditContours([line(p(0, 0), p(10, 0)), line(p(10, 0), p(20, 0), 'b'), line(p(10, 0), p(10, 10), 'c')]).some(i => i.kind === 'branch'));
const branch = W.joinContours([line(p(0, 0), p(10, 0)), line(p(10, 0), p(20, 0), 'b'), line(p(10, 0), p(10, 10), 'c')]); assert.equal(branch.entities.length, 3);
const scale = W.measurementScale([{ measured: 10, actual: 20 }, { measured: 15, actual: 30 }]); near(scale.factor, 2); near(scale.rms, 0);
assert.ok(W.measurementScale([{ measured: 10, actual: 20 }, { measured: 15, actual: 35 }]).rms > 1);
assert.throws(() => W.measurementScale([{ measured: 0, actual: 10 }, { measured: 2, actual: 10 }]));
const corners = [p(10, 20), p(200, 40), p(180, 160), p(20, 150)];
const map = W.homography(corners, 100, 60);
[[0, 0], [100, 0], [100, 60], [0, 60]].forEach(([x, y], i) => near(G.dist(map(x, y), corners[i]), 0));
assert.throws(() => W.homography([p(0, 0), p(1, 1), p(0, 1), p(1, 0)], 10, 10));
const image = W.imagePoint(p(0, 10), { x: 0, y: 0, wMM: 10, hMM: 20, rotation: Math.PI / 2 }, { naturalWidth: 100, naturalHeight: 200 }); near(image.x, 100); near(image.y, 0);
const loop = Array.from({ length: 101 }, (_, i) => p(Math.cos(i / 100 * 2 * Math.PI) * 20, Math.sin(i / 100 * 2 * Math.PI) * 20));
assert.ok(W.fitTrace(loop, { mode: 'fit', tol: 0.2, cornerDeg: 40, close: true }).some(e => e.type === 'circle' || e.closed));
assert.ok(W.fitTrace(loop, { mode: 'fit', tol: 0.2, cornerDeg: 40, close: false }).every(e => e.type !== 'circle' && !e.closed));
console.log('workflows: PASS (alignment, fidelity, contours, arc joins, calibration, perspective)');
